// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: unused_field
// ignore_for_file: unused_element
// Auto-generated FFI bindings - do not edit manually

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// FFI bindings for Gosh Authenticator Rust core
class GoshFfiBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  GoshFfiBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  GoshFfiBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void gosh_init_logging() {
    return _gosh_init_logging();
  }

  late final _gosh_init_loggingPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('gosh_init_logging');
  late final _gosh_init_logging =
      _gosh_init_loggingPtr.asFunction<void Function()>();

  ffi.Pointer<GoshClient> gosh_client_new() {
    return _gosh_client_new();
  }

  late final _gosh_client_newPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<GoshClient> Function()>>(
          'gosh_client_new');
  late final _gosh_client_new =
      _gosh_client_newPtr.asFunction<ffi.Pointer<GoshClient> Function()>();

  void gosh_client_free(
    ffi.Pointer<GoshClient> client,
  ) {
    return _gosh_client_free(
      client,
    );
  }

  late final _gosh_client_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GoshClient>)>>(
          'gosh_client_free');
  late final _gosh_client_free =
      _gosh_client_freePtr.asFunction<void Function(ffi.Pointer<GoshClient>)>();

  void gosh_client_set_callback(
    ffi.Pointer<GoshClient> client,
    GoshEventCallback callback,
    ffi.Pointer<ffi.Void> user_data,
  ) {
    return _gosh_client_set_callback(
      client,
      callback,
      user_data,
    );
  }

  late final _gosh_client_set_callbackPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<GoshClient>, GoshEventCallback,
              ffi.Pointer<ffi.Void>)>>('gosh_client_set_callback');
  late final _gosh_client_set_callback =
      _gosh_client_set_callbackPtr.asFunction<
          void Function(ffi.Pointer<GoshClient>, GoshEventCallback,
              ffi.Pointer<ffi.Void>)>();

  void gosh_client_connect(
    ffi.Pointer<GoshClient> client,
  ) {
    return _gosh_client_connect(
      client,
    );
  }

  late final _gosh_client_connectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GoshClient>)>>(
          'gosh_client_connect');
  late final _gosh_client_connect = _gosh_client_connectPtr
      .asFunction<void Function(ffi.Pointer<GoshClient>)>();

  void gosh_client_refresh(
    ffi.Pointer<GoshClient> client,
  ) {
    return _gosh_client_refresh(
      client,
    );
  }

  late final _gosh_client_refreshPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GoshClient>)>>(
          'gosh_client_refresh');
  late final _gosh_client_refresh = _gosh_client_refreshPtr
      .asFunction<void Function(ffi.Pointer<GoshClient>)>();

  void gosh_client_authenticate(
    ffi.Pointer<GoshClient> client,
    ffi.Pointer<ffi.Char> password,
  ) {
    return _gosh_client_authenticate(
      client,
      password,
    );
  }

  late final _gosh_client_authenticatePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<GoshClient>,
              ffi.Pointer<ffi.Char>)>>('gosh_client_authenticate');
  late final _gosh_client_authenticate =
      _gosh_client_authenticatePtr.asFunction<
          void Function(ffi.Pointer<GoshClient>, ffi.Pointer<ffi.Char>)>();

  void gosh_client_calculate(
    ffi.Pointer<GoshClient> client,
    ffi.Pointer<ffi.Uint8> id_ptr,
    int id_len,
  ) {
    return _gosh_client_calculate(
      client,
      id_ptr,
      id_len,
    );
  }

  late final _gosh_client_calculatePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<GoshClient>, ffi.Pointer<ffi.Uint8>,
              ffi.Size)>>('gosh_client_calculate');
  late final _gosh_client_calculate = _gosh_client_calculatePtr.asFunction<
      void Function(ffi.Pointer<GoshClient>, ffi.Pointer<ffi.Uint8>, int)>();

  void gosh_client_delete_credential(
    ffi.Pointer<GoshClient> client,
    ffi.Pointer<ffi.Uint8> id_ptr,
    int id_len,
  ) {
    return _gosh_client_delete_credential(
      client,
      id_ptr,
      id_len,
    );
  }

  late final _gosh_client_delete_credentialPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<GoshClient>, ffi.Pointer<ffi.Uint8>,
              ffi.Size)>>('gosh_client_delete_credential');
  late final _gosh_client_delete_credential =
      _gosh_client_delete_credentialPtr.asFunction<
          void Function(
              ffi.Pointer<GoshClient>, ffi.Pointer<ffi.Uint8>, int)>();

  bool gosh_client_add_credential(
    ffi.Pointer<GoshClient> client,
    ffi.Pointer<ffi.Char> issuer,
    ffi.Pointer<ffi.Char> account,
    ffi.Pointer<ffi.Char> secret,
    int oath_type,
    int algorithm,
    int digits,
    int require_touch,
    int initial_counter,
    int has_initial_counter,
  ) {
    return _gosh_client_add_credential(
      client,
      issuer,
      account,
      secret,
      oath_type,
      algorithm,
      digits,
      require_touch,
      initial_counter,
      has_initial_counter,
    );
  }

  late final _gosh_client_add_credentialPtr = _lookup<
      ffi.NativeFunction<
          ffi.Bool Function(
              ffi.Pointer<GoshClient>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Uint8,
              ffi.Uint8,
              ffi.Uint8,
              ffi.Uint8,
              ffi.Uint32,
              ffi.Uint8)>>('gosh_client_add_credential');
  late final _gosh_client_add_credential =
      _gosh_client_add_credentialPtr.asFunction<
          bool Function(
              ffi.Pointer<GoshClient>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              int,
              int,
              int,
              int,
              int,
              int)>();

  ffi.Pointer<ffi.Char> gosh_client_last_error_take(
    ffi.Pointer<GoshClient> client,
  ) {
    return _gosh_client_last_error_take(
      client,
    );
  }

  late final _gosh_client_last_error_takePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<GoshClient>)>>('gosh_client_last_error_take');
  late final _gosh_client_last_error_take = _gosh_client_last_error_takePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<GoshClient>)>();

  void gosh_string_free(
    ffi.Pointer<ffi.Char> value,
  ) {
    return _gosh_string_free(
      value,
    );
  }

  late final _gosh_string_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'gosh_string_free');
  late final _gosh_string_free =
      _gosh_string_freePtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  void gosh_event_free(
    ffi.Pointer<GoshEvent> event,
  ) {
    return _gosh_event_free(
      event,
    );
  }

  late final _gosh_event_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<GoshEvent>)>>(
          'gosh_event_free');
  late final _gosh_event_free =
      _gosh_event_freePtr.asFunction<void Function(ffi.Pointer<GoshEvent>)>();
}

final class GoshVersion extends ffi.Struct {
  @ffi.Uint8()
  external int major;

  @ffi.Uint8()
  external int minor;

  @ffi.Uint8()
  external int patch;
}

final class GoshCredential extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> id_ptr;

  @ffi.Size()
  external int id_len;

  external ffi.Pointer<ffi.Char> issuer;

  external ffi.Pointer<ffi.Char> account;

  external ffi.Pointer<ffi.Char> code;

  @ffi.Uint8()
  external int oath_type;

  @ffi.Uint8()
  external int algorithm;

  @ffi.Uint8()
  external int digits;

  @ffi.Uint8()
  external int touch_required;

  @ffi.Uint32()
  external int period;
}

final class GoshEvent extends ffi.Struct {
  @ffi.Uint32()
  external int event_type;

  external GoshVersion version;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> device_id;

  external ffi.Pointer<ffi.Char> message;

  external ffi.Pointer<GoshCredential> credentials;

  @ffi.Size()
  external int credentials_len;

  external ffi.Pointer<ffi.Uint8> id_ptr;

  @ffi.Size()
  external int id_len;

  external ffi.Pointer<ffi.Char> code;

  @ffi.Uint8()
  external int digits;
}

final class GoshClient extends ffi.Opaque {}

typedef GoshEventCallback
    = ffi.Pointer<ffi.NativeFunction<GoshEventCallbackFunction>>;
typedef GoshEventCallbackFunction = ffi.Void Function(
    ffi.Pointer<GoshEvent> event, ffi.Pointer<ffi.Void> user_data);
typedef DartGoshEventCallbackFunction = void Function(
    ffi.Pointer<GoshEvent> event, ffi.Pointer<ffi.Void> user_data);

const int __bool_true_false_are_defined = 1;

const int true1 = 1;

const int false1 = 0;

const int NULL = 0;

const int _STDINT_H = 1;

const int _FEATURES_H = 1;

const int _DEFAULT_SOURCE = 1;

const int __GLIBC_USE_ISOC2Y = 1;

const int __GLIBC_USE_ISOC23 = 1;

const int __USE_ISOC11 = 1;

const int __USE_ISOC99 = 1;

const int __USE_ISOC95 = 1;

const int _POSIX_SOURCE = 1;

const int _POSIX_C_SOURCE = 200809;

const int __USE_POSIX = 1;

const int __USE_POSIX2 = 1;

const int __USE_POSIX199309 = 1;

const int __USE_POSIX199506 = 1;

const int __USE_XOPEN2K = 1;

const int __USE_XOPEN2K8 = 1;

const int _ATFILE_SOURCE = 1;

const int __WORDSIZE = 64;

const int __WORDSIZE_TIME64_COMPAT32 = 1;

const int __SYSCALL_WORDSIZE = 64;

const int __TIMESIZE = 64;

const int __USE_TIME_BITS64 = 1;

const int __USE_MISC = 1;

const int __USE_ATFILE = 1;

const int __USE_FORTIFY_LEVEL = 0;

const int __GLIBC_USE_DEPRECATED_GETS = 0;

const int __GLIBC_USE_DEPRECATED_SCANF = 0;

const int __GLIBC_USE_C23_STRTOL = 1;

const int _STDC_PREDEF_H = 1;

const int __STDC_IEC_559__ = 1;

const int __STDC_IEC_60559_BFP__ = 201404;

const int __STDC_IEC_559_COMPLEX__ = 1;

const int __STDC_IEC_60559_COMPLEX__ = 201404;

const int __STDC_ISO_10646__ = 201706;

const int __GNU_LIBRARY__ = 6;

const int __GLIBC__ = 2;

const int __GLIBC_MINOR__ = 42;

const int _SYS_CDEFS_H = 1;

const int __THROW = 1;

const int __THROWNL = 1;

const int __glibc_c99_flexarr_available = 1;

const int __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI = 0;

const int __HAVE_GENERIC_SELECTION = 0;

const int __GLIBC_USE_LIB_EXT2 = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT = 1;

const int __GLIBC_USE_IEC_60559_BFP_EXT_C23 = 1;

const int __GLIBC_USE_IEC_60559_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT = 1;

const int __GLIBC_USE_IEC_60559_FUNCS_EXT_C23 = 1;

const int __GLIBC_USE_IEC_60559_TYPES_EXT = 1;

const int _BITS_TYPES_H = 1;

const int _BITS_TYPESIZES_H = 1;

const int __OFF_T_MATCHES_OFF64_T = 1;

const int __INO_T_MATCHES_INO64_T = 1;

const int __RLIM_T_MATCHES_RLIM64_T = 1;

const int __STATFS_MATCHES_STATFS64 = 1;

const int __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64 = 1;

const int __FD_SETSIZE = 1024;

const int _BITS_TIME64_H = 1;

const int _BITS_WCHAR_H = 1;

const int __WCHAR_MAX = 2147483647;

const int __WCHAR_MIN = -2147483648;

const int _BITS_STDINT_INTN_H = 1;

const int _BITS_STDINT_UINTN_H = 1;

const int _BITS_STDINT_LEAST_H = 1;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -9223372036854775808;

const int INT_FAST32_MIN = -9223372036854775808;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 9223372036854775807;

const int INT_FAST32_MAX = 9223372036854775807;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = -1;

const int UINT_FAST32_MAX = -1;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MIN = -9223372036854775808;

const int INTPTR_MAX = 9223372036854775807;

const int UINTPTR_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int SIZE_MAX = -1;

const int WCHAR_MIN = -2147483648;

const int WCHAR_MAX = 2147483647;

const int WINT_MIN = 0;

const int WINT_MAX = 4294967295;
